### ISSUE TITLE
Doesn't support user or password for elasticsearch output

### ISSUE THREAD

**Issue by morganchristiansson** [mrlesmithjr/ansible-es-packetbeat#2]

**Comment by mrlesmithjr** [comment]
@morganchristiansson Thanks for this as well. I will look into this.

**Comment by morganchristiansson** [comment]
Maybe something similar to what this filebeat role has done would be easier https://github.com/DavidWittman/ansible-filebeat

**Comment by mrlesmithjr** [comment]
@morganchristiansson Added. Thanks again for pointing this out.
